"""create inventory tables

Revision ID: 0b3cad604b77
Revises: a9f5136bc290
Create Date: 2026-07-13 00:12:52.195169

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3cad604b77'
down_revision: str | None = 'a9f5136bc290'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_grams', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('input_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('input_unit', sa.String(length=20), nullable=False),
    sa.Column('purchased_at', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_inventory_items_ingredient_id_ingredients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inventory_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items'))
    )
    op.create_index('idx_inventory_items_user_ingredient_expires', 'inventory_items', ['user_id', 'ingredient_id', 'expires_at'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('inventory_item_id', sa.BigInteger(), nullable=True),
    sa.Column('delta_grams', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('source_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_inventory_transactions_ingredient_id_ingredients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_inventory_transactions_inventory_item_id_inventory_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_entry_id'], ['meal_plan_entries.id'], name=op.f('fk_inventory_transactions_source_entry_id_meal_plan_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inventory_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_transactions'))
    )
    op.create_index('idx_inventory_transactions_occurred', 'inventory_transactions', ['occurred_at'], unique=False)
    op.create_index('idx_inventory_transactions_source_entry', 'inventory_transactions', ['source_entry_id'], unique=False)
    op.create_index('idx_inventory_transactions_user_ingredient_time', 'inventory_transactions', ['user_id', 'ingredient_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_inventory_transactions_user_ingredient_time', table_name='inventory_transactions')
    op.drop_index('idx_inventory_transactions_source_entry', table_name='inventory_transactions')
    op.drop_index('idx_inventory_transactions_occurred', table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index('idx_inventory_items_user_ingredient_expires', table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
