"""add shopping tables

Revision ID: 1338b40ff5cc
Revises: e43bb8446f56
Create Date: 2026-07-27 13:34:59.959909

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1338b40ff5cc'
down_revision: str | None = 'e43bb8446f56'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_lists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('source_meal_plan_id', sa.BigInteger(), nullable=True),
    sa.Column('forecast_start', sa.Date(), nullable=True),
    sa.Column('forecast_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(forecast_start IS NULL) = (forecast_end IS NULL) AND (forecast_end IS NULL OR forecast_end >= forecast_start)', name=op.f('ck_shopping_lists_forecast_range')),
    sa.ForeignKeyConstraint(['source_meal_plan_id'], ['meal_plans.id'], name=op.f('fk_shopping_lists_source_meal_plan_id_meal_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shopping_lists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_lists'))
    )
    op.create_index('idx_shopping_lists_user_status', 'shopping_lists', ['user_id', 'status'], unique=False)
    op.create_table('shopping_list_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shopping_list_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=True),
    sa.Column('item_name', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('needed_grams', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('add_to_inventory', sa.Boolean(), nullable=False),
    sa.Column('is_purchased', sa.Boolean(), nullable=False),
    sa.Column('purchased_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchased_unit', sa.String(length=20), nullable=True),
    sa.Column('purchased_grams', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category_override', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ingredient_id IS NOT NULL OR item_name IS NOT NULL', name=op.f('ck_shopping_list_items_has_identity')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_shopping_list_items_ingredient_id_ingredients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], name=op.f('fk_shopping_list_items_shopping_list_id_shopping_lists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_list_items'))
    )
    op.create_index('idx_shopping_list_items_auto_dedup', 'shopping_list_items', ['shopping_list_id', 'ingredient_id'], unique=True, postgresql_where=sa.text("source = 'auto' AND ingredient_id IS NOT NULL AND is_purchased = false"))
    op.create_index('idx_shopping_list_items_list', 'shopping_list_items', ['shopping_list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_shopping_list_items_list', table_name='shopping_list_items')
    op.drop_index('idx_shopping_list_items_auto_dedup', table_name='shopping_list_items', postgresql_where=sa.text("source = 'auto' AND ingredient_id IS NOT NULL AND is_purchased = false"))
    op.drop_table('shopping_list_items')
    op.drop_index('idx_shopping_lists_user_status', table_name='shopping_lists')
    op.drop_table('shopping_lists')
    # ### end Alembic commands ###
