"""create ingredients table

Revision ID: 153bf345acc5
Revises: 911b07ee6f47
Create Date: 2026-06-16 19:26:58.320918

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153bf345acc5'
down_revision: str | None = '911b07ee6f47'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_normalized', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('per_100g_calories', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('per_100g_protein', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('per_100g_carbs', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('per_100g_fat', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('default_unit', sa.String(length=20), server_default=sa.text("'g'"), nullable=False),
    sa.Column('grams_per_unit', sa.Numeric(precision=7, scale=2), server_default=sa.text('1.0'), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'user'"), nullable=False),
    sa.Column('usda_fdc_id', sa.String(length=20), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients'))
    )
    op.create_index('idx_ingredients_category', 'ingredients', ['category'], unique=False)
    op.create_index('idx_ingredients_name_normalized', 'ingredients', ['name_normalized'], unique=False)
    op.create_index('idx_ingredients_source', 'ingredients', ['source'], unique=False)
    op.create_index('idx_ingredients_usda_fdc_id', 'ingredients', ['usda_fdc_id'], unique=True, postgresql_where=sa.text('usda_fdc_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ingredients_usda_fdc_id', table_name='ingredients', postgresql_where=sa.text('usda_fdc_id IS NOT NULL'))
    op.drop_index('idx_ingredients_source', table_name='ingredients')
    op.drop_index('idx_ingredients_name_normalized', table_name='ingredients')
    op.drop_index('idx_ingredients_category', table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
