"""create recipe tables

Revision ID: 64c868f9d733
Revises: 153bf345acc5
Create Date: 2026-06-17 15:22:37.449317

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c868f9d733'
down_revision: str | None = '153bf345acc5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cuisine', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('ai_generation_log_id', sa.BigInteger(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes'))
    )
    op.create_index('idx_recipes_created_by', 'recipes', ['created_by_user_id'], unique=False)
    op.create_index('idx_recipes_name', 'recipes', ['name'], unique=False)
    op.create_index('idx_recipes_source', 'recipes', ['source'], unique=False)
    op.create_table('recipe_variants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('purpose_tag', sa.String(length=30), nullable=False),
    sa.Column('extra_notes', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('cooking_time_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('total_calories', sa.Numeric(precision=7, scale=1), nullable=True),
    sa.Column('total_protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_carbs_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_grams', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('nutrition_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_variants_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_variants'))
    )
    op.create_index('idx_recipe_variants_purpose_tag', 'recipe_variants', ['purpose_tag'], unique=False)
    op.create_index('idx_recipe_variants_recipe_id', 'recipe_variants', ['recipe_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('recipe_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_grams', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('input_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('input_unit', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_recipe_ingredients_ingredient_id_ingredients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_variant_id'], ['recipe_variants.id'], name=op.f('fk_recipe_ingredients_recipe_variant_id_recipe_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredients'))
    )
    op.create_index('idx_recipe_ingredients_ingredient_id', 'recipe_ingredients', ['ingredient_id'], unique=False)
    op.create_index('idx_recipe_ingredients_variant_id', 'recipe_ingredients', ['recipe_variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recipe_ingredients_variant_id', table_name='recipe_ingredients')
    op.drop_index('idx_recipe_ingredients_ingredient_id', table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index('idx_recipe_variants_recipe_id', table_name='recipe_variants')
    op.drop_index('idx_recipe_variants_purpose_tag', table_name='recipe_variants')
    op.drop_table('recipe_variants')
    op.drop_index('idx_recipes_source', table_name='recipes')
    op.drop_index('idx_recipes_name', table_name='recipes')
    op.drop_index('idx_recipes_created_by', table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
