"""add user body fields and nutrition goals

Revision ID: 842633d6643a
Revises: 64c868f9d733
Create Date: 2026-06-17 20:31:27.212347

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842633d6643a'
down_revision: str | None = '64c868f9d733'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_nutrition_goals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.String(length=20), nullable=False),
    sa.Column('daily_calories', sa.Numeric(precision=7, scale=1), nullable=False),
    sa.Column('daily_protein_g', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('daily_carbs_g', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('daily_fat_g', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('is_custom', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_nutrition_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_nutrition_goals')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_nutrition_goals_user_id'))
    )
    op.add_column('users', sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('users', sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('biological_sex', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('activity_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activity_level')
    op.drop_column('users', 'biological_sex')
    op.drop_column('users', 'age')
    op.drop_column('users', 'weight_kg')
    op.drop_column('users', 'height_cm')
    op.drop_table('user_nutrition_goals')
    # ### end Alembic commands ###
