"""create meal plan tables

Revision ID: a9f5136bc290
Revises: 842633d6643a
Create Date: 2026-06-19 20:42:23.200494

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f5136bc290'
down_revision: str | None = '842633d6643a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('ai_generation_log_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_meal_plans_chk_date_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meal_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_plans'))
    )
    op.create_index('idx_meal_plans_template', 'meal_plans', ['user_id', 'is_template'], unique=False, postgresql_where=sa.text('is_template = true'))
    op.create_index('idx_meal_plans_user_dates', 'meal_plans', ['user_id', 'start_date', 'end_date'], unique=False)
    op.create_table('meal_plan_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('meal_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('recipe_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('servings', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], name=op.f('fk_meal_plan_entries_meal_plan_id_meal_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_variant_id'], ['recipe_variants.id'], name=op.f('fk_meal_plan_entries_recipe_variant_id_recipe_variants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_plan_entries'))
    )
    op.create_index('idx_meal_plan_entries_completed', 'meal_plan_entries', ['meal_plan_id', 'is_completed'], unique=False)
    op.create_index('idx_meal_plan_entries_plan_date', 'meal_plan_entries', ['meal_plan_id', 'scheduled_date'], unique=False)
    op.create_index('idx_meal_plan_entries_variant', 'meal_plan_entries', ['recipe_variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_meal_plan_entries_variant', table_name='meal_plan_entries')
    op.drop_index('idx_meal_plan_entries_plan_date', table_name='meal_plan_entries')
    op.drop_index('idx_meal_plan_entries_completed', table_name='meal_plan_entries')
    op.drop_table('meal_plan_entries')
    op.drop_index('idx_meal_plans_user_dates', table_name='meal_plans')
    op.drop_index('idx_meal_plans_template', table_name='meal_plans', postgresql_where=sa.text('is_template = true'))
    op.drop_table('meal_plans')
    # ### end Alembic commands ###
