"""add location and transaction created_at

Revision ID: e43bb8446f56
Revises: 7ce8329404eb
Create Date: 2026-07-24 13:48:21.990027

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e43bb8446f56'
down_revision: str | None = '7ce8329404eb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('location', sa.String(length=20), nullable=True))
    op.add_column('inventory_transactions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_transactions', 'created_at')
    op.drop_column('inventory_items', 'location')
    # ### end Alembic commands ###
